language: erlang

before_install:
  - git submodule update --init --recursive
  - ./configure
  - make -C out

script:
  - exit 0

notifications:
  email:
    - ryan.phillips@rackspace.com
  irc:
    - chat.freenode.net#virgo-dev
